<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5f689545-4676-4956-a6ad-ebbae6af0424</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Caslu.IA.Application\Caslu.IA.Application.csproj" />
    <ProjectReference Include="..\Caslu.IA.Infrastructure\Caslu.IA.Infrastructure.csproj" />
  </ItemGroup>

</Project>
